CREATE DATABASE BCP;

use BCP;

CREATE TABLE Cuenta(
	NRO_CUENTA NVARCHAR(14) NOT NULL PRIMARY KEY,
	TIPO CHAR(3) NOT NULL,
	MONEDA CHAR(3) NOT NULL,
	NOMBRE NVARCHAR(40) NOT NULL,
	SALDO DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE Movimiento(
	NRO_CUENTA NVARCHAR(14) NOT NULL FOREIGN KEY REFERENCES Cuenta(NRO_CUENTA),
	FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIPO CHAR(1) NOT NULL,
	IMPORTE DECIMAL(12,2) NOT NULL,

	CONSTRAINT PK_movimiento PRIMARY KEY (NRO_CUENTA,fecha)
);




/************* PROCEDURES *************/
CREATE PROCEDURE CrearCuenta
	@NRO_CUENTA NVARCHAR(14),
	@TIPO CHAR(3),
	@MONEDA CHAR(3),
	@NOMBRE NVARCHAR(40)
AS
INSERT INTO Cuenta (NRO_CUENTA,TIPO,MONEDA,NOMBRE) VALUES (@NRO_CUENTA,@TIPO,@MONEDA,@NOMBRE)
GO

CREATE PROCEDURE DepositarORetirar
	@NRO_CUENTA NVARCHAR(14),
	@TIPO CHAR(1),
	@IMPORTE DECIMAL(12,2)
AS
BEGIN
	IF (@TIPO = 'A')
	BEGIN
		UPDATE Cuenta SET SALDO=SALDO+@IMPORTE WHERE NRO_CUENTA=@NRO_CUENTA
	END
	ELSE BEGIN
		UPDATE Cuenta SET SALDO=SALDO-@IMPORTE WHERE NRO_CUENTA=@NRO_CUENTA
	END

	INSERT INTO Movimiento (NRO_CUENTA,TIPO,IMPORTE) VALUES (@NRO_CUENTA,@TIPO,@IMPORTE)
END
GO

CREATE PROCEDURE Transferir
	@NRO_CUENTA_ORIGEN NVARCHAR(14),
	@NRO_CUENTA_DESTINO NVARCHAR(14),
	@MONTO DECIMAL(12,2)
AS
BEGIN
	EXEC DepositarORetirar @NRO_CUENTA = @NRO_CUENTA_ORIGEN, @TIPO = 'D', @IMPORTE = @MONTO;

	EXEC DepositarORetirar @NRO_CUENTA = @NRO_CUENTA_DESTINO, @TIPO = 'A', @IMPORTE = @MONTO;
END
GO

CREATE PROCEDURE ObtenerCuentas
AS
SELECT * FROM Cuenta
GO

CREATE PROCEDURE ObtenerMovimientos
	@NRO_CUENTA NVARCHAR(14)
AS
SELECT * FROM Movimiento WHERE NRO_CUENTA=@NRO_CUENTA 
GO


CREATE PROCEDURE EncontrarCuenta
	@NRO_CUENTA NVARCHAR(14)
AS
SELECT * FROM Cuenta WHERE NRO_CUENTA=@NRO_CUENTA 
GO


/**************** OTHER TABLES *******************/
CREATE TABLE TipoCambio(
	ID INT NOT NULL PRIMARY KEY,
	COMPRA DECIMAL(12,2) NOT NULL,
	VENTA DECIMAL(12,2) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL
);
CREATE TABLE Moneda(
	CODE CHAR(3) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL,

	CAMBIO INT FOREIGN KEY REFERENCES TipoCambio(ID)
);

